default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: time_management_system_development

test:
  <<: *default
  database: time_management_system_test

staging:
  <<: *default
  database: time_management_system_staging
  sslmode: "require"

production:
  <<: *default
  database: time_management_system_production
  sslmode: "require"

